line-length = 160
indent-width = 4

[lint]
select = [
    "UP007",  # Use of 'Union[type, type]' instead of 'type | type'
    'E721',   # Use `is` and `is not` for type comparisons, or `isinstance()` for isinstance checks
    'UP028',  # Replace `yield` over `for` loop with `yield from`
    # UP008 Use `super()` instead of `super(__class__, self)`
    'UP032',  # Use f-string instead of `format` call
    'UP034',  # Avoid extraneous parentheses

    'DOC202', # docstring states a return value the function doesnt return
    'DOC403', # docstring states a yield the function doesnt yield

    'W',      # warnings, mostly niggly pep8 annoyances
    'E3',     # blank lines before function/class definition
    'E4',     # imports
    'E5',     # line too long, redundant backslash
    'E7',     # comparisons
    'E9',
]
ignore = [
    'E731',  # dont assign lambda's, use a function def
    'E722',  # dont use a bare except
]