"""
Copyright 2019 Zeppelin Bend Pty Ltd
This file is part of cimbend.

cimbend is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

cimbend is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with cimbend.  If not, see <https://www.gnu.org/licenses/>.
"""


# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zepben/cim/iec61968/metering/MeterReading.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from zepben.cim.iec61968.metering import Reading_pb2 as zepben_dot_cim_dot_iec61968_dot_metering_dot_Reading__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='zepben/cim/iec61968/metering/MeterReading.proto',
  package='zepben.cim.iec61968.metering',
  syntax='proto3',
  serialized_options=_b('\n)com.zepben.protobuf.cim.iec61968.meteringP\001'),
  serialized_pb=_b('\n/zepben/cim/iec61968/metering/MeterReading.proto\x12\x1czepben.cim.iec61968.metering\x1a*zepben/cim/iec61968/metering/Reading.proto\"v\n\x0cMeterReading\x12\x0c\n\x04mRID\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tmeterMRID\x18\x03 \x01(\t\x12\x37\n\x08readings\x18\x05 \x03(\x0b\x32%.zepben.cim.iec61968.metering.ReadingB-\n)com.zepben.protobuf.cim.iec61968.meteringP\x01\x62\x06proto3')
  ,
  dependencies=[zepben_dot_cim_dot_iec61968_dot_metering_dot_Reading__pb2.DESCRIPTOR,])




_METERREADING = _descriptor.Descriptor(
  name='MeterReading',
  full_name='zepben.cim.iec61968.metering.MeterReading',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mRID', full_name='zepben.cim.iec61968.metering.MeterReading.mRID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='zepben.cim.iec61968.metering.MeterReading.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meterMRID', full_name='zepben.cim.iec61968.metering.MeterReading.meterMRID', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='readings', full_name='zepben.cim.iec61968.metering.MeterReading.readings', index=3,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=243,
)

_METERREADING.fields_by_name['readings'].message_type = zepben_dot_cim_dot_iec61968_dot_metering_dot_Reading__pb2._READING
DESCRIPTOR.message_types_by_name['MeterReading'] = _METERREADING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MeterReading = _reflection.GeneratedProtocolMessageType('MeterReading', (_message.Message,), {
  'DESCRIPTOR' : _METERREADING,
  '__module__' : 'zepben.cim.iec61968.metering.MeterReading_pb2'
  # @@protoc_insertion_point(class_scope:zepben.cim.iec61968.metering.MeterReading)
  })
_sym_db.RegisterMessage(MeterReading)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
