"""
Copyright 2019 Zeppelin Bend Pty Ltd
This file is part of cimbend.

cimbend is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

cimbend is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with cimbend.  If not, see <https://www.gnu.org/licenses/>.
"""


# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zepben/cim/iec61968/metering/Reading.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='zepben/cim/iec61968/metering/Reading.proto',
  package='zepben.cim.iec61968.metering',
  syntax='proto3',
  serialized_options=_b('\n)com.zepben.protobuf.cim.iec61968.meteringP\001'),
  serialized_pb=_b('\n*zepben/cim/iec61968/metering/Reading.proto\x12\x1czepben.cim.iec61968.metering\x1a\x1fgoogle/protobuf/timestamp.proto\"G\n\x07Reading\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05value\x18\x02 \x01(\x01\x42-\n)com.zepben.protobuf.cim.iec61968.meteringP\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_READING = _descriptor.Descriptor(
  name='Reading',
  full_name='zepben.cim.iec61968.metering.Reading',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='zepben.cim.iec61968.metering.Reading.timestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='zepben.cim.iec61968.metering.Reading.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=180,
)

_READING.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['Reading'] = _READING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Reading = _reflection.GeneratedProtocolMessageType('Reading', (_message.Message,), {
  'DESCRIPTOR' : _READING,
  '__module__' : 'zepben.cim.iec61968.metering.Reading_pb2'
  # @@protoc_insertion_point(class_scope:zepben.cim.iec61968.metering.Reading)
  })
_sym_db.RegisterMessage(Reading)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
