"""
Copyright 2019 Zeppelin Bend Pty Ltd
This file is part of cimbend.

cimbend is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

cimbend is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with cimbend.  If not, see <https://www.gnu.org/licenses/>.
"""


# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zepben/cim/iec61970/base/diagramlayout/Diagram.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from zepben.cim.iec61970.base.diagramlayout import DiagramStyle_pb2 as zepben_dot_cim_dot_iec61970_dot_base_dot_diagramlayout_dot_DiagramStyle__pb2
from zepben.cim.iec61970.base.diagramlayout import OrientationKind_pb2 as zepben_dot_cim_dot_iec61970_dot_base_dot_diagramlayout_dot_OrientationKind__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='zepben/cim/iec61970/base/diagramlayout/Diagram.proto',
  package='zepben.cim.iec61970.base.diagramlayout',
  syntax='proto3',
  serialized_options=_b('\n3com.zepben.protobuf.cim.iec61970.base.diagramlayoutP\001'),
  serialized_pb=_b('\n4zepben/cim/iec61970/base/diagramlayout/Diagram.proto\x12&zepben.cim.iec61970.base.diagramlayout\x1a\x39zepben/cim/iec61970/base/diagramlayout/DiagramStyle.proto\x1a<zepben/cim/iec61970/base/diagramlayout/OrientationKind.proto\"\xc3\x01\n\x07\x44iagram\x12\x0c\n\x04mRID\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12J\n\x0c\x64iagramStyle\x18\x03 \x01(\x0e\x32\x34.zepben.cim.iec61970.base.diagramlayout.DiagramStyle\x12P\n\x0forientationKind\x18\x04 \x01(\x0e\x32\x37.zepben.cim.iec61970.base.diagramlayout.OrientationKindB7\n3com.zepben.protobuf.cim.iec61970.base.diagramlayoutP\x01\x62\x06proto3')
  ,
  dependencies=[zepben_dot_cim_dot_iec61970_dot_base_dot_diagramlayout_dot_DiagramStyle__pb2.DESCRIPTOR,zepben_dot_cim_dot_iec61970_dot_base_dot_diagramlayout_dot_OrientationKind__pb2.DESCRIPTOR,])




_DIAGRAM = _descriptor.Descriptor(
  name='Diagram',
  full_name='zepben.cim.iec61970.base.diagramlayout.Diagram',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mRID', full_name='zepben.cim.iec61970.base.diagramlayout.Diagram.mRID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='zepben.cim.iec61970.base.diagramlayout.Diagram.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='diagramStyle', full_name='zepben.cim.iec61970.base.diagramlayout.Diagram.diagramStyle', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orientationKind', full_name='zepben.cim.iec61970.base.diagramlayout.Diagram.orientationKind', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=413,
)

_DIAGRAM.fields_by_name['diagramStyle'].enum_type = zepben_dot_cim_dot_iec61970_dot_base_dot_diagramlayout_dot_DiagramStyle__pb2._DIAGRAMSTYLE
_DIAGRAM.fields_by_name['orientationKind'].enum_type = zepben_dot_cim_dot_iec61970_dot_base_dot_diagramlayout_dot_OrientationKind__pb2._ORIENTATIONKIND
DESCRIPTOR.message_types_by_name['Diagram'] = _DIAGRAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Diagram = _reflection.GeneratedProtocolMessageType('Diagram', (_message.Message,), {
  'DESCRIPTOR' : _DIAGRAM,
  '__module__' : 'zepben.cim.iec61970.base.diagramlayout.Diagram_pb2'
  # @@protoc_insertion_point(class_scope:zepben.cim.iec61970.base.diagramlayout.Diagram)
  })
_sym_db.RegisterMessage(Diagram)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
