"""
Copyright 2019 Zeppelin Bend Pty Ltd
This file is part of cimbend.

cimbend is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

cimbend is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with cimbend.  If not, see <https://www.gnu.org/licenses/>.
"""


# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zepben/cim/iec61970/base/diagramlayout/DiagramObject.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from zepben.cim.iec61970.base.diagramlayout import DiagramObjectPoint_pb2 as zepben_dot_cim_dot_iec61970_dot_base_dot_diagramlayout_dot_DiagramObjectPoint__pb2
from zepben.cim.iec61970.base.diagramlayout import DiagramObjectStyle_pb2 as zepben_dot_cim_dot_iec61970_dot_base_dot_diagramlayout_dot_DiagramObjectStyle__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='zepben/cim/iec61970/base/diagramlayout/DiagramObject.proto',
  package='zepben.cim.iec61970.base.diagramlayout',
  syntax='proto3',
  serialized_options=_b('\n3com.zepben.protobuf.cim.iec61970.base.diagramlayoutP\001'),
  serialized_pb=_b('\n:zepben/cim/iec61970/base/diagramlayout/DiagramObject.proto\x12&zepben.cim.iec61970.base.diagramlayout\x1a?zepben/cim/iec61970/base/diagramlayout/DiagramObjectPoint.proto\x1a?zepben/cim/iec61970/base/diagramlayout/DiagramObjectStyle.proto\"\xa1\x02\n\rDiagramObject\x12\x0c\n\x04mRID\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64iagramMRID\x18\x03 \x01(\t\x12\x1c\n\x14identifiedObjectMRID\x18\x04 \x01(\t\x12V\n\x12\x64iagramObjectStyle\x18\x05 \x01(\x0e\x32:.zepben.cim.iec61970.base.diagramlayout.DiagramObjectStyle\x12\x10\n\x08rotation\x18\x06 \x01(\x01\x12W\n\x13\x64iagramObjectPoints\x18\x10 \x03(\x0b\x32:.zepben.cim.iec61970.base.diagramlayout.DiagramObjectPointB7\n3com.zepben.protobuf.cim.iec61970.base.diagramlayoutP\x01\x62\x06proto3')
  ,
  dependencies=[zepben_dot_cim_dot_iec61970_dot_base_dot_diagramlayout_dot_DiagramObjectPoint__pb2.DESCRIPTOR,zepben_dot_cim_dot_iec61970_dot_base_dot_diagramlayout_dot_DiagramObjectStyle__pb2.DESCRIPTOR,])




_DIAGRAMOBJECT = _descriptor.Descriptor(
  name='DiagramObject',
  full_name='zepben.cim.iec61970.base.diagramlayout.DiagramObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mRID', full_name='zepben.cim.iec61970.base.diagramlayout.DiagramObject.mRID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='zepben.cim.iec61970.base.diagramlayout.DiagramObject.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='diagramMRID', full_name='zepben.cim.iec61970.base.diagramlayout.DiagramObject.diagramMRID', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='identifiedObjectMRID', full_name='zepben.cim.iec61970.base.diagramlayout.DiagramObject.identifiedObjectMRID', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='diagramObjectStyle', full_name='zepben.cim.iec61970.base.diagramlayout.DiagramObject.diagramObjectStyle', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rotation', full_name='zepben.cim.iec61970.base.diagramlayout.DiagramObject.rotation', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='diagramObjectPoints', full_name='zepben.cim.iec61970.base.diagramlayout.DiagramObject.diagramObjectPoints', index=6,
      number=16, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=522,
)

_DIAGRAMOBJECT.fields_by_name['diagramObjectStyle'].enum_type = zepben_dot_cim_dot_iec61970_dot_base_dot_diagramlayout_dot_DiagramObjectStyle__pb2._DIAGRAMOBJECTSTYLE
_DIAGRAMOBJECT.fields_by_name['diagramObjectPoints'].message_type = zepben_dot_cim_dot_iec61970_dot_base_dot_diagramlayout_dot_DiagramObjectPoint__pb2._DIAGRAMOBJECTPOINT
DESCRIPTOR.message_types_by_name['DiagramObject'] = _DIAGRAMOBJECT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DiagramObject = _reflection.GeneratedProtocolMessageType('DiagramObject', (_message.Message,), {
  'DESCRIPTOR' : _DIAGRAMOBJECT,
  '__module__' : 'zepben.cim.iec61970.base.diagramlayout.DiagramObject_pb2'
  # @@protoc_insertion_point(class_scope:zepben.cim.iec61970.base.diagramlayout.DiagramObject)
  })
_sym_db.RegisterMessage(DiagramObject)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
