#  Copyright 2025 Zeppelin Bend Pty Ltd
#  This Source Code Form is subject to the terms of the Mozilla Public
#  License, v. 2.0. If a copy of the MPL was not distributed with this
#  file, You can obtain one at https://mozilla.org/MPL/2.0/.
from abc import ABC

from zepben.ewb.database.sqlite.tables.sqlite_table import SqliteTable
from zepben.ewb.database.sql.column import Type, Column, Nullable


class TableContactDetails(SqliteTable, ABC):
    """
    A class representing the `ContactDetails` columns required for the database table.

    :var id: A column storing the identifier for this contact, could be autogenerated.
    :var contact_type: A column storing the type of contact, e.g. Account Owner.
    :var first_name: A column storing the first name of the contact.
    :var last_name: A column storing the last name of the contact.
    :var preferred_contact_method: A column storing the preferred contact method for this contact.
    :var is_primary: A column storing whether this contact is a primary contact.
    :var business_name: A column storing the business name of this contact.
    """
    def __init__(self):
        self.id: Column = self._create_column('id', Type.STRING, Nullable.NOT_NULL)
        self.contact_type = self._create_column('contact_type', Type.STRING, Nullable.NULL)
        self.first_name = self._create_column('first_name', Type.STRING, Nullable.NULL)
        self.last_name = self._create_column('last_name', Type.STRING, Nullable.NULL)
        self.preferred_contact_method = self._create_column('preferred_contact_method', Type.STRING, Nullable.NULL)
        self.is_primary = self._create_column('is_primary', Type.BOOLEAN, Nullable.NULL)
        self.business_name = self._create_column('business_name', Type.STRING, Nullable.NULL)
