"""
Copyright 2019 Zeppelin Bend Pty Ltd
This file is part of cimbend.

cimbend is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

cimbend is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with cimbend.  If not, see <https://www.gnu.org/licenses/>.
"""


# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zepben/cim/iec61970/base/domain/CurrentFlow.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='zepben/cim/iec61970/base/domain/CurrentFlow.proto',
  package='zepben.cim.iec61970.base.domain',
  syntax='proto3',
  serialized_options=_b('\n,com.zepben.protobuf.cim.iec61970.base.domainP\001'),
  serialized_pb=_b('\n1zepben/cim/iec61970/base/domain/CurrentFlow.proto\x12\x1fzepben.cim.iec61970.base.domain\"\x1c\n\x0b\x43urrentFlow\x12\r\n\x05value\x18\x01 \x01(\x01\x42\x30\n,com.zepben.protobuf.cim.iec61970.base.domainP\x01\x62\x06proto3')
)




_CURRENTFLOW = _descriptor.Descriptor(
  name='CurrentFlow',
  full_name='zepben.cim.iec61970.base.domain.CurrentFlow',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='zepben.cim.iec61970.base.domain.CurrentFlow.value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=114,
)

DESCRIPTOR.message_types_by_name['CurrentFlow'] = _CURRENTFLOW
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CurrentFlow = _reflection.GeneratedProtocolMessageType('CurrentFlow', (_message.Message,), {
  'DESCRIPTOR' : _CURRENTFLOW,
  '__module__' : 'zepben.cim.iec61970.base.domain.CurrentFlow_pb2'
  # @@protoc_insertion_point(class_scope:zepben.cim.iec61970.base.domain.CurrentFlow)
  })
_sym_db.RegisterMessage(CurrentFlow)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
