"""
Copyright 2019 Zeppelin Bend Pty Ltd
This file is part of cimbend.

cimbend is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

cimbend is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with cimbend.  If not, see <https://www.gnu.org/licenses/>.
"""


# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zepben/cim/iec61968/assetinfo/WireMaterialKind.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='zepben/cim/iec61968/assetinfo/WireMaterialKind.proto',
  package='zepben.cim.iec61968.assetinfo',
  syntax='proto3',
  serialized_options=_b('\n*com.zepben.protobuf.cim.iec61968.assetinfoP\001'),
  serialized_pb=_b('\n4zepben/cim/iec61968/assetinfo/WireMaterialKind.proto\x12\x1dzepben.cim.iec61968.assetinfo*\xc0\x01\n\x10WireMaterialKind\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04\x61\x61\x61\x63\x10\x01\x12\x08\n\x04\x61\x63sr\x10\x02\x12\n\n\x06\x61\x63srAz\x10\x03\x12\x0c\n\x08\x61luminum\x10\x04\x12\x11\n\raluminumAlloy\x10\x05\x12\x16\n\x12\x61luminumAlloySteel\x10\x06\x12\x11\n\raluminumSteel\x10\x07\x12\n\n\x06\x63opper\x10\x08\x12\x11\n\rcopperCadmium\x10\t\x12\t\n\x05other\x10\n\x12\t\n\x05steel\x10\x0b\x42.\n*com.zepben.protobuf.cim.iec61968.assetinfoP\x01\x62\x06proto3')
)

_WIREMATERIALKIND = _descriptor.EnumDescriptor(
  name='WireMaterialKind',
  full_name='zepben.cim.iec61968.assetinfo.WireMaterialKind',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='aaac', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='acsr', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='acsrAz', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='aluminum', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='aluminumAlloy', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='aluminumAlloySteel', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='aluminumSteel', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='copper', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='copperCadmium', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='other', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='steel', index=11, number=11,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=88,
  serialized_end=280,
)
_sym_db.RegisterEnumDescriptor(_WIREMATERIALKIND)

WireMaterialKind = enum_type_wrapper.EnumTypeWrapper(_WIREMATERIALKIND)
UNKNOWN = 0
aaac = 1
acsr = 2
acsrAz = 3
aluminum = 4
aluminumAlloy = 5
aluminumAlloySteel = 6
aluminumSteel = 7
copper = 8
copperCadmium = 9
other = 10
steel = 11


DESCRIPTOR.enum_types_by_name['WireMaterialKind'] = _WIREMATERIALKIND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
