"""
Copyright 2019 Zeppelin Bend Pty Ltd
This file is part of cimbend.

cimbend is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

cimbend is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with cimbend.  If not, see <https://www.gnu.org/licenses/>.
"""


# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zepben/cim/iec61970/base/core/Terminal.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from zepben.cim.iec61970.base.core import PhaseCode_pb2 as zepben_dot_cim_dot_iec61970_dot_base_dot_core_dot_PhaseCode__pb2
from zepben.cim.iec61970.base.wires import Direction_pb2 as zepben_dot_cim_dot_iec61970_dot_base_dot_wires_dot_Direction__pb2
from zepben.cim.iec61970.base.diagramlayout import DiagramObject_pb2 as zepben_dot_cim_dot_iec61970_dot_base_dot_diagramlayout_dot_DiagramObject__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='zepben/cim/iec61970/base/core/Terminal.proto',
  package='zepben.cim.iec61970.base.core',
  syntax='proto3',
  serialized_options=_b('\n*com.zepben.protobuf.cim.iec61970.base.coreP\001'),
  serialized_pb=_b('\n,zepben/cim/iec61970/base/core/Terminal.proto\x12\x1dzepben.cim.iec61970.base.core\x1a-zepben/cim/iec61970/base/core/PhaseCode.proto\x1a.zepben/cim/iec61970/base/wires/Direction.proto\x1a:zepben/cim/iec61970/base/diagramlayout/DiagramObject.proto\"\xa8\x02\n\x08Terminal\x12\x0c\n\x04mRID\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tconnected\x18\x03 \x01(\x08\x12\x1c\n\x14\x63onnectivityNodeMRID\x18\x04 \x01(\t\x12\x38\n\x06phases\x18\x05 \x01(\x0e\x32(.zepben.cim.iec61970.base.core.PhaseCode\x12\x46\n\tdirection\x18\x06 \x03(\x0e\x32\x33.zepben.cim.iec61970.base.wires.direction.Direction\x12M\n\x0e\x64iagramObjects\x18\x10 \x03(\x0b\x32\x35.zepben.cim.iec61970.base.diagramlayout.DiagramObjectB.\n*com.zepben.protobuf.cim.iec61970.base.coreP\x01\x62\x06proto3')
  ,
  dependencies=[zepben_dot_cim_dot_iec61970_dot_base_dot_core_dot_PhaseCode__pb2.DESCRIPTOR,zepben_dot_cim_dot_iec61970_dot_base_dot_wires_dot_Direction__pb2.DESCRIPTOR,zepben_dot_cim_dot_iec61970_dot_base_dot_diagramlayout_dot_DiagramObject__pb2.DESCRIPTOR,])




_TERMINAL = _descriptor.Descriptor(
  name='Terminal',
  full_name='zepben.cim.iec61970.base.core.Terminal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mRID', full_name='zepben.cim.iec61970.base.core.Terminal.mRID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='zepben.cim.iec61970.base.core.Terminal.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='connected', full_name='zepben.cim.iec61970.base.core.Terminal.connected', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='connectivityNodeMRID', full_name='zepben.cim.iec61970.base.core.Terminal.connectivityNodeMRID', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='phases', full_name='zepben.cim.iec61970.base.core.Terminal.phases', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='direction', full_name='zepben.cim.iec61970.base.core.Terminal.direction', index=5,
      number=6, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='diagramObjects', full_name='zepben.cim.iec61970.base.core.Terminal.diagramObjects', index=6,
      number=16, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=531,
)

_TERMINAL.fields_by_name['phases'].enum_type = zepben_dot_cim_dot_iec61970_dot_base_dot_core_dot_PhaseCode__pb2._PHASECODE
_TERMINAL.fields_by_name['direction'].enum_type = zepben_dot_cim_dot_iec61970_dot_base_dot_wires_dot_Direction__pb2._DIRECTION
_TERMINAL.fields_by_name['diagramObjects'].message_type = zepben_dot_cim_dot_iec61970_dot_base_dot_diagramlayout_dot_DiagramObject__pb2._DIAGRAMOBJECT
DESCRIPTOR.message_types_by_name['Terminal'] = _TERMINAL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Terminal = _reflection.GeneratedProtocolMessageType('Terminal', (_message.Message,), {
  'DESCRIPTOR' : _TERMINAL,
  '__module__' : 'zepben.cim.iec61970.base.core.Terminal_pb2'
  # @@protoc_insertion_point(class_scope:zepben.cim.iec61970.base.core.Terminal)
  })
_sym_db.RegisterMessage(Terminal)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
