"""
Copyright 2019 Zeppelin Bend Pty Ltd
This file is part of cimbend.

cimbend is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

cimbend is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with cimbend.  If not, see <https://www.gnu.org/licenses/>.
"""


# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zepben/cim/iec61970/base/wires/PhaseShuntConnectionKind.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='zepben/cim/iec61970/base/wires/PhaseShuntConnectionKind.proto',
  package='zepben.cim.iec61970.base.wires',
  syntax='proto3',
  serialized_options=_b('\n+com.zepben.protobuf.cim.iec61970.base.wiresP\001'),
  serialized_pb=_b('\n=zepben/cim/iec61970/base/wires/PhaseShuntConnectionKind.proto\x12\x1ezepben.cim.iec61970.base.wires*>\n\x18PhaseShuntConnectionKind\x12\x05\n\x01\x44\x10\x00\x12\x05\n\x01Y\x10\x01\x12\x06\n\x02Yn\x10\x02\x12\x05\n\x01I\x10\x03\x12\x05\n\x01G\x10\x04\x42/\n+com.zepben.protobuf.cim.iec61970.base.wiresP\x01\x62\x06proto3')
)

_PHASESHUNTCONNECTIONKIND = _descriptor.EnumDescriptor(
  name='PhaseShuntConnectionKind',
  full_name='zepben.cim.iec61970.base.wires.PhaseShuntConnectionKind',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='D', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Y', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Yn', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='I', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='G', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=97,
  serialized_end=159,
)
_sym_db.RegisterEnumDescriptor(_PHASESHUNTCONNECTIONKIND)

PhaseShuntConnectionKind = enum_type_wrapper.EnumTypeWrapper(_PHASESHUNTCONNECTIONKIND)
D = 0
Y = 1
Yn = 2
I = 3
G = 4


DESCRIPTOR.enum_types_by_name['PhaseShuntConnectionKind'] = _PHASESHUNTCONNECTIONKIND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
