"""
Copyright 2019 Zeppelin Bend Pty Ltd
This file is part of cimbend.

cimbend is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

cimbend is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with cimbend.  If not, see <https://www.gnu.org/licenses/>.
"""


# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zepben/cim/iec61970/base/wires/WindingConnection.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='zepben/cim/iec61970/base/wires/WindingConnection.proto',
  package='zepben.cim.iec61970.base.wires.winding',
  syntax='proto3',
  serialized_options=_b('\n+com.zepben.protobuf.cim.iec61970.base.wiresP\001'),
  serialized_pb=_b('\n6zepben/cim/iec61970/base/wires/WindingConnection.proto\x12&zepben.cim.iec61970.base.wires.winding*[\n\x11WindingConnection\x12\x13\n\x0fUNKNOWN_WINDING\x10\x00\x12\x05\n\x01\x44\x10\x01\x12\x05\n\x01Y\x10\x02\x12\x05\n\x01Z\x10\x03\x12\x06\n\x02Yn\x10\x04\x12\x06\n\x02Zn\x10\x05\x12\x05\n\x01\x41\x10\x06\x12\x05\n\x01I\x10\x07\x42/\n+com.zepben.protobuf.cim.iec61970.base.wiresP\x01\x62\x06proto3')
)

_WINDINGCONNECTION = _descriptor.EnumDescriptor(
  name='WindingConnection',
  full_name='zepben.cim.iec61970.base.wires.winding.WindingConnection',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_WINDING', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='D', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Y', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Z', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Yn', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Zn', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='A', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='I', index=7, number=7,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=98,
  serialized_end=189,
)
_sym_db.RegisterEnumDescriptor(_WINDINGCONNECTION)

WindingConnection = enum_type_wrapper.EnumTypeWrapper(_WINDINGCONNECTION)
UNKNOWN_WINDING = 0
D = 1
Y = 2
Z = 3
Yn = 4
Zn = 5
A = 6
I = 7


DESCRIPTOR.enum_types_by_name['WindingConnection'] = _WINDINGCONNECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
