#  Copyright 2025 Zeppelin Bend Pty Ltd
#  This Source Code Form is subject to the terms of the Mozilla Public
#  License, v. 2.0. If a copy of the MPL was not distributed with this
#  file, You can obtain one at https://mozilla.org/MPL/2.0/.

__all__ = ["ContactDetails"]

from collections.abc import Hashable
from typing import Generator, Any
from zepben.ewb.util import ngen, nlen
from zepben.ewb.dataclassy import dataclass
from zepben.ewb.model.cim.extensions.zbex import zbex
from zepben.ewb.model.cim.iec61968.common.electronic_address import ElectronicAddress
from zepben.ewb.model.cim.iec61968.common.street_address import StreetAddress

from zepben.ewb.model.cim.extensions.iec61968.common.contact_method_type import ContactMethodType
from zepben.ewb.model.cim.iec61968.common.telephone_number import TelephoneNumber


@zbex
@dataclass(slots=True)
class ContactDetails:
    """[ZBEX] The details required to contact a person or company."""

    id: str
    """[ZBEX] The identifier for this contact, could be autogenerated."""

    contact_address: StreetAddress | None = None
    """[ZBEX] Contact address, potentially different than 'streetAddress' (e.g., another city)."""

    contact_type: str | None = None
    """[ZBEX] The type of contact, e.g. Account Owner."""

    first_name: str | None = None
    """[ZBEX] First name of the contact."""

    last_name: str | None = None
    """[ZBEX] Last name of the contact."""

    preferred_contact_method: ContactMethodType = ContactMethodType.UNKNOWN
    """[ZBEX] The preferred contact method for this contact."""

    is_primary: bool | None = None
    """[ZBEX] Whether this contact is a primary contact."""

    business_name: str | None = None
    """[ZBEX] The business name of this contact."""

    _phone_numbers: list[TelephoneNumber] | None = None

    _electronic_addresses: list[ElectronicAddress] | None = None

    def __init__(self, phone_numbers: list[TelephoneNumber] = None, electronic_addresses: list[ElectronicAddress] = None):
        for number in phone_numbers or []:
            self.add_phone_number(number)

        for email in electronic_addresses or []:
            self.add_electronic_address(email)

    def __str__(self):
        return f"ContactDetails({self.id})"

    def __hash__(self):
        return hash((type(self), *(getattr(self, s ) for s in self.__slots__)))

    @property
    def phone_numbers(self) -> Generator[TelephoneNumber, None, None]:
        return ngen(self._phone_numbers)

    @property
    def num_phone_numbers(self) -> int:
        """Get the number of entries in the ``TelephoneNumber`` collection."""
        return nlen(self._phone_numbers)

    def add_phone_number(self, phone_number: TelephoneNumber) -> "ContactDetails":
        """
        Add an ``TelephoneNumber`` to this ``ContactDetails``.

        :param phone_number: The ``TelephoneNumber`` to add.
        :return: This ``ContactDetails`` for fluent use.
        """
        if self._phone_numbers is None:
            self._phone_numbers = []
        self._phone_numbers.append(phone_number)
        return self

    def remove_phone_number(self, phone_number: TelephoneNumber) -> bool:
        """
        Remove an ``TelephoneNumber`` from this ``ContactDetails``.
        :param phone_number: The ``TelephoneNumber`` to remove.
        :return: True if the ``TelephoneNumber`` was removed.
        """
        try:
            self._phone_numbers.remove(phone_number)
            if self.num_phone_numbers == 0:
                self._phone_numbers = None
            return True
        except ValueError:
            return False

    def clear_phone_numbers(self) -> "ContactDetails":
        """
        Clear all ``TelephoneNumber``'s from this ``ContactDetails``.
        :return: this ``ContactDetails`` for fluent use.
        """
        self._phone_numbers = None
        return self

    @property
    def electronic_addresses(self) -> Generator[ElectronicAddress, None, None]:
        return ngen(self._electronic_addresses)

    def num_electronic_addresses(self) -> int:
        """Get the number of entries in the [ElectronicAddress] collection."""
        return nlen(self._electronic_addresses)

    def add_electronic_address(self, electronic_address: ElectronicAddress) -> "ContactDetails":
        """
        Add an ``ElectronicAddress`` to this ``ContactDetails``.
        :param electronic_address: The ``ElectronicAddress`` to add.
        :return: this ``ContactDetails`` for fluent use.
        """
        if self._electronic_addresses is None:
            self._electronic_addresses = []
        self._electronic_addresses.append(electronic_address)
        return self

    def remove_electronic_address(self, electronic_address: ElectronicAddress) -> bool:
        """
        Remove an ``ElectronicAddress`` from this ``ContactDetails``.
        :param electronic_address: The ``ElectronicAddress`` to remove.
        :return: True if the ``ElectronicAddress`` was removed.
        """
        try:
            self._electronic_addresses.remove(electronic_address)
            if self.num_electronic_addresses == 0:
                self._electronic_addresses = None
            return True
        except ValueError:
            return False

    def clear_electronic_addresses(self) -> "ContactDetails":
        """
        Clear all ``ElectronicAddress``'s from this ``ContactDetails``.

        :return: this ``ContactDetails`` for fluent use.
        """
        self._electronic_addresses = None
        return self

    def __eq__(self, other: Any) -> bool:
        #
        # NOTE: We implement the equals to allow us to compare the entire ``ContactDetails`` as a value. We do this since it isnt an
        #       ``IdentifiedObject``, so our other helpers don't support it.
        if not isinstance(other, ContactDetails):
            return False
        return all((
            self.is_primary == other.is_primary,
            self.id == other.id,
            self.contact_address == other.contact_address,
            self.contact_type == other.contact_type,
            self.first_name == other.first_name,
            self.last_name == other.last_name,
            self.preferred_contact_method == other.preferred_contact_method,
            self.business_name == other.business_name,
            self._phone_numbers == other._phone_numbers,
            self._electronic_addresses == other._electronic_addresses,
        ))
    