#  Copyright 2025 Zeppelin Bend Pty Ltd
#  This Source Code Form is subject to the terms of the Mozilla Public
#  License, v. 2.0. If a copy of the MPL was not distributed with this
#  file, You can obtain one at https://mozilla.org/MPL/2.0/.

__all__ = ["ContactDetails"]

from dataclasses import field
from typing import Any

from typing_extensions import deprecated

from zepben.ewb import zb_dataclass
from zepben.ewb.boilerplate.collections.abstract_backed_list import AbstractBackedList
from zepben.ewb.boilerplate.collections.lazy_collection import LazyCollection
from zepben.ewb.model.cim.extensions.iec61968.common.contact_method_type import ContactMethodType
from zepben.ewb.model.cim.extensions.zbex import zbex
from zepben.ewb.model.cim.iec61968.common.electronic_address import ElectronicAddress
from zepben.ewb.model.cim.iec61968.common.street_address import StreetAddress
from zepben.ewb.model.cim.iec61968.common.telephone_number import TelephoneNumber
from zepben.ewb.model.cim.iec61970.base.core.identifiable import Identifiable


@zbex
@zb_dataclass
class ContactDetails(Identifiable):
    """[ZBEX] The details required to contact a person or company.

    :var id: [ZBEX] The identifier for this contact, could be autogenerated.
    :var contact_address: [ZBEX] Contact address, potentially different than 'streetAddress' (e.g., another city).
    :var contact_type: [ZBEX] The type of contact, e.g. Account Owner.
    :var first_name: [ZBEX] First name of the contact.
    :var last_name: [ZBEX] Last name of the contact.
    :var preferred_contact_method: [ZBEX] The preferred contact method for this contact.
    :var is_primary: [ZBEX] Whether this contact is a primary contact.
    :var business_name: [ZBEX] The business name of this contact.
    :var phone_numbers: [ZBEX] Phone numbers.
    :var electronic_addresses: [ZBEX] Electronic addresses.
    """

    @property
    @deprecated("Use obj.mrid instead")
    def id(self) -> str:
        """[ZBEX] The identifier for this contact, could be autogenerated."""
        return self.mrid

    contact_address: StreetAddress | None = None
    """[ZBEX] Contact address, potentially different than 'streetAddress' (e.g., another city)."""

    contact_type: str | None = None
    """[ZBEX] The type of contact, e.g. Account Owner."""

    first_name: str | None = None
    """[ZBEX] First name of the contact."""

    last_name: str | None = None
    """[ZBEX] Last name of the contact."""

    preferred_contact_method: ContactMethodType = ContactMethodType.UNKNOWN
    """[ZBEX] The preferred contact method for this contact."""

    is_primary: bool | None = None
    """[ZBEX] Whether this contact is a primary contact."""

    business_name: str | None = None
    """[ZBEX] The business name of this contact."""

    _phone_numbers: list[TelephoneNumber] | None = field(default=None)

    phone_numbers: AbstractBackedList[TelephoneNumber] = LazyCollection(_phone_numbers)
    """[ZBEX] Phone numbers."""

    _electronic_addresses: list[ElectronicAddress] | None = field(default=None)

    electronic_addresses: AbstractBackedList[ElectronicAddress] = LazyCollection(_electronic_addresses)
    """[ZBEX] Electronic addresses."""

    def __init__(self, id: str|None=None, *args, **kwargs):
        if id is not None:
            if "mrid" in kwargs:
                raise TypeError("ContactDetails.id is an alias for mrid. Do not pass both to the constructor!")
            kwargs["mrid"] = id
        super(ContactDetails, self).__init__(*args, **kwargs)


    def __str__(self):
        return f"ContactDetails({self.mrid})"

    def __hash__(self):
        # noinspection PyUnresolvedReferences
        return hash((type(self), *(getattr(self, s) for s in self.__slots__)))


    def __eq__(self, other: Any) -> bool:
        #
        # NOTE: We implement the equals to allow us to compare the entire ``ContactDetails`` as a value. We do this since it isnt an
        #       ``IdentifiedObject``, so our other helpers don't support it.
        if not isinstance(other, ContactDetails):
            return False
        return all((
            self.is_primary == other.is_primary,
            self.mrid == other.mrid,
            self.contact_address == other.contact_address,
            self.contact_type == other.contact_type,
            self.first_name == other.first_name,
            self.last_name == other.last_name,
            self.preferred_contact_method == other.preferred_contact_method,
            self.business_name == other.business_name,
            self._phone_numbers == other._phone_numbers,
            self._electronic_addresses == other._electronic_addresses,
        ))


    # region deprecated list boilerplate

    # region phone_numbers boilerplate

    @deprecated("Use len(phone_numbers) instead.")
    def num_phone_numbers(self) -> int:
        return len(self.phone_numbers)

    @deprecated("Use phone_numbers.append(phone_number) instead.")
    def add_phone_number(
        self,
        phone_number: TelephoneNumber,
    ) -> "ContactDetails":
        self.phone_numbers.append(phone_number)
        return self

    @deprecated("Use phone_numbers.remove(phone_number) instead.")
    def remove_phone_number(
        self,
        phone_number: TelephoneNumber,
    ) -> bool:
        self.phone_numbers.remove(phone_number)
        return True

    @deprecated("Use phone_numbers.clear() instead.")
    def clear_phone_numbers(self) -> "ContactDetails":
        self.phone_numbers.clear()
        return self

    # endregion

    # region electronic_addresses boilerplate

    @deprecated("Use len(electronic_addresses) instead.")
    def num_electronic_addresses(self) -> int:
        return len(self.electronic_addresses)

    @deprecated("Use electronic_addresses.append(electronic_address) instead.")
    def add_electronic_address(
        self,
        electronic_address: ElectronicAddress,
    ) -> "ContactDetails":
        self.electronic_addresses.append(electronic_address)
        return self

    @deprecated("Use electronic_addresses.remove(electronic_address) instead.")
    def remove_electronic_address(
        self,
        electronic_address: ElectronicAddress,
    ) -> bool:
        self.electronic_addresses.remove(electronic_address)
        return True

    @deprecated("Use electronic_addresses.clear() instead.")
    def clear_electronic_addresses(self) -> "ContactDetails":
        self.electronic_addresses.clear()
        return self

    # endregion

    # endregion
