name: Python Library Release

on: workflow_dispatch

jobs:
  run:
    uses: zepben/.github/.github/workflows/python-lib-release-with-docs.yml@main
    with:
      private: false
      product-key: "python-sdk"   # Must be unique
    secrets: inherit
